#!/usr/bin/env bash
# Compound System - 多平台配置向导
# 用法: setup.sh [--provider <provider>] [--non-interactive]

set -e

COMPOUND_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[SETUP]${NC} $1"; }
log_success() { echo -e "${GREEN}[SETUP]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[SETUP]${NC} $1"; }
log_error() { echo -e "${RED}[SETUP]${NC} $1"; }

# 支持的 LLM 提供商
declare -A PROVIDERS=(
    ["deepseek"]="DeepSeek|https://api.deepseek.com/v1|deepseek-chat"
    ["openai"]="OpenAI|https://api.openai.com/v1|gpt-4o-mini"
    ["xiaomi"]="小米 MIMO (Token Plan)|https://token-plan-cn.xiaomimimo.com/v1|mimo-v2.5"
    ["xiaomi-sk"]="小米 MIMO (SK)|https://api.xiaomimimo.com/v1|mimo-v2.5"
    ["anthropic"]="Anthropic|https://api.anthropic.com/v1|claude-3-haiku-20240307"
    ["custom"]="自定义 OpenAI 兼容 API||"
)

# 检测 Python 命令
detect_python() {
    if command -v python3 &>/dev/null; then
        echo "python3"
    elif command -v python &>/dev/null; then
        echo "python"
    else
        log_error "Python not found. Please install Python 3."
        exit 1
    fi
}

# 检测操作系统
detect_os() {
    case "$OSTYPE" in
        msys*|cygwin*|win*) echo "windows" ;;
        darwin*) echo "macos" ;;
        linux*) echo "linux" ;;
        *) echo "unknown" ;;
    esac
}

# 生成配置文件
generate_config() {
    local provider="$1"
    local api_key="$2"
    local endpoint="$3"
    local model="$4"

    cat > "$COMPOUND_ROOT/.env" << EOF
# Compound System - LLM API Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# Provider: $provider
# Documentation: https://github.com/lennney/compound-system

# LLM API Configuration
LLM_API_KEY=$api_key
LLM_ENDPOINT=$endpoint
LLM_MODEL=$model

# Optional: Custom settings
# LLM_TEMPERATURE=0.3
# LLM_MAX_TOKENS=2000
EOF

    log_success "Configuration saved to $COMPOUND_ROOT/.env"
}

# 交互式配置
interactive_setup() {
    echo ""
    echo "=========================================="
    echo "  Compound System - 配置向导"
    echo "=========================================="
    echo ""
    echo "选择 LLM 提供商:"
    echo ""

    local i=1
    local -a provider_keys=()
    for key in deepseek openai xiaomi xiaomi-sk anthropic custom; do
        IFS='|' read -r name endpoint model <<< "${PROVIDERS[$key]}"
        echo "  $i) $name"
        provider_keys+=("$key")
        ((i++))
    done

    echo ""
    read -p "请输入编号 (1-${#provider_keys[@]}): " choice

    if [[ "$choice" -lt 1 || "$choice" -gt ${#provider_keys[@]} ]]; then
        log_error "无效选择"
        exit 1
    fi

    local selected_key="${provider_keys[$((choice-1))]}"
    IFS='|' read -r name endpoint model <<< "${PROVIDERS[$selected_key]}"

    echo ""
    echo "选择的提供商: $name"
    echo ""

    # 获取 API Key
    read -p "请输入 API Key: " api_key
    if [[ -z "$api_key" ]]; then
        log_error "API Key 不能为空"
        exit 1
    fi

    # 自定义 endpoint 和 model
    if [[ "$selected_key" == "custom" ]]; then
        read -p "请输入 API Endpoint: " endpoint
        read -p "请输入 Model 名称: " model
    else
        read -p "API Endpoint [$endpoint]: " custom_endpoint
        read -p "Model [$model]: " custom_model
        endpoint="${custom_endpoint:-$endpoint}"
        model="${custom_model:-$model}"
    fi

    # 生成配置
    generate_config "$name" "$api_key" "$endpoint" "$model"

    # 测试连接
    echo ""
    log_info "测试 API 连接..."
    test_connection "$api_key" "$endpoint" "$model"
}

# 非交互式配置
non_interactive_setup() {
    local provider="$1"

    if [[ -z "${PROVIDERS[$provider]}" ]]; then
        log_error "未知提供商: $provider"
        echo "可用提供商: ${!PROVIDERS[*]}"
        exit 1
    fi

    IFS='|' read -r name endpoint model <<< "${PROVIDERS[$provider]}"

    # 从环境变量获取 API Key
    local api_key="${LLM_API_KEY:-}"
    if [[ -z "$api_key" ]]; then
        log_error "请设置 LLM_API_KEY 环境变量"
        exit 1
    fi

    # 允许自定义 endpoint 和 model
    endpoint="${LLM_ENDPOINT:-$endpoint}"
    model="${LLM_MODEL:-$model}"

    generate_config "$name" "$api_key" "$endpoint" "$model"
}

# 测试连接
test_connection() {
    local api_key="$1"
    local endpoint="$2"
    local model="$3"
    local PYTHON_CMD=$(detect_python)

    $PYTHON_CMD << PYEOF
import json, urllib.request, sys

api_key = "$api_key"
endpoint = "$endpoint"
model = "$model"

data = json.dumps({
    'model': model,
    'messages': [{'role': 'user', 'content': 'Hello'}],
    'max_tokens': 10
}).encode('utf-8')

try:
    req = urllib.request.Request(
        f'{endpoint}/chat/completions',
        data=data,
        headers={
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {api_key}'
        }
    )
    resp = urllib.request.urlopen(req, timeout=10)
    result = json.loads(resp.read())
    print(f"✅ 连接成功! Model: {result.get('model', 'unknown')}")
except Exception as e:
    print(f"❌ 连接失败: {e}")
    sys.exit(1)
PYEOF
}

# 显示帮助
show_help() {
    echo "Compound System - 多平台配置向导"
    echo ""
    echo "用法:"
    echo "  setup.sh [选项]"
    echo ""
    echo "选项:"
    echo "  --provider <name>    指定提供商 (非交互式)"
    echo "  --test               测试当前配置"
    echo "  --show               显示当前配置"
    echo "  --help               显示帮助"
    echo ""
    echo "支持的提供商:"
    for key in deepseek openai xiaomi xiaomi-sk anthropic custom; do
        IFS='|' read -r name endpoint model <<< "${PROVIDERS[$key]}"
        echo "  $key - $name"
    done
    echo ""
    echo "环境变量:"
    echo "  LLM_API_KEY          API Key (非交互式必需)"
    echo "  LLM_ENDPOINT         自定义 Endpoint"
    echo "  LLM_MODEL            自定义 Model"
    echo ""
    echo "示例:"
    echo "  # 交互式配置"
    echo "  ./scripts/setup.sh"
    echo ""
    echo "  # 非交互式配置"
    echo "  LLM_API_KEY=xxx ./scripts/setup.sh --provider deepseek"
    echo ""
    echo "  # 测试当前配置"
    echo "  ./scripts/setup.sh --test"
}

# 测试当前配置
test_current_config() {
    if [[ ! -f "$COMPOUND_ROOT/.env" ]]; then
        log_error "配置文件不存在，请先运行 setup.sh"
        exit 1
    fi

    source "$COMPOUND_ROOT/.env"

    if [[ -z "${LLM_API_KEY:-}" ]]; then
        log_error "LLM_API_KEY 未配置"
        exit 1
    fi

    log_info "测试当前配置..."
    test_connection "$LLM_API_KEY" "${LLM_ENDPOINT:-https://api.deepseek.com/v1}" "${LLM_MODEL:-deepseek-chat}"
}

# 显示当前配置
show_config() {
    if [[ ! -f "$COMPOUND_ROOT/.env" ]]; then
        log_warn "配置文件不存在"
        return
    fi

    echo "当前配置:"
    echo "=========================================="
    grep -E "^LLM_" "$COMPOUND_ROOT/.env" | sed 's/=/: /'
    echo "=========================================="
}

# 主函数
main() {
    local provider=""
    local action="interactive"

    # 解析参数
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --provider)
                provider="$2"
                action="non-interactive"
                shift 2
                ;;
            --test)
                action="test"
                shift
                ;;
            --show)
                action="show"
                shift
                ;;
            --help|-h)
                show_help
                exit 0
                ;;
            *)
                log_error "未知参数: $1"
                show_help
                exit 1
                ;;
        esac
    done

    # 执行操作
    case "$action" in
        interactive)
            interactive_setup
            ;;
        non-interactive)
            non_interactive_setup "$provider"
            ;;
        test)
            test_current_config
            ;;
        show)
            show_config
            ;;
    esac
}

# 运行
main "$@"
